name: NUBO
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7538
title: NUBO GmbH - Office 365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c6249'
    - '#010302'
    - '#f9fdf9'
    - '#a58a66'
    - '#c3c4c2'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
