name: NUBO
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23965
title: NUBO GmbH - Office 365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbb040'
    - '#fbc26d'
    - '#fccc83'
    - '#fcd396'
    - '#fdddae'
  brandStrength: 1
  lightness: 0.9568153901491314
  saturation: 0.5
  rhythmicContrast: 0.5808386229909956
purpose: []
