name: NUBO
favicon: null
layout_spectrum: 0.74654
typography_spectrum: 0.90792
title: NUBO GmbH - Office 365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbb040'
    - '#ffffff'
    - '#ff0000'
    - '#ff8000'
    - '#ffff00'
  brandStrength: 0.625
  lightness: 0.9568153901491314
  saturation: 0.5
  rhythmicContrast: 0.5808386229909956
purpose: []
